apiVersion: v1
kind: Secret
metadata:
  name: portal-keycloak-admin-secret
  namespace: portal
type: Opaque
stringData:
  KEYCLOAK_ADMIN_CLIENT_SECRET: replace-with-data-platform-admin-api-client-secret
