apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespaces.yaml
  - postgres.yaml
  - spark-manager.yaml
  - deploy.yaml

images:
  - name: data-portal-app
    newName: ghcr.io/your-org/data-platform-app
    newTag: latest
